#!/usr/bin/with-contenv bash

# download and unpack
echo "[cont-init.d] Downloading and unpacking"

if [ ! -f "/music_library_tools/music_library_tools/daemons.py" ]; then
    echo "[cont-init.d] First start, cloning repo"
    git clone  https://github.com/sasanjac/music-library-tools /music_library_tools
    cd /music_library_tools
    poetry install --no-dev
else
    cd /music_library_tools
    localv=$(git rev-parse HEAD)
    remotev=$(git ls-remote https://github.com/sasanjac/music-library-tools.git refs/heads/main | cut -c1-40)
    if [ $localv = $remotev ]; then
        echo -e "[cont-init.d] Latest Version. No update needed"
    else
        echo -e "[cont-init.d] Newer Version. Updating"
        git pull
        poetry install --no-dev
    fi
fi
