#!/usr/bin/with-contenv bash

# set home of the abc user
usermod -d /music_library_tools abc

# permissions
echo "[cont-init.d] Setting permissions this may take some time"

chown -R abc:abc /music_library_tools/
chown -R abc:abc /.config/
