#!/usr/bin/with-contenv bash

if [ -f "/music_library_tools/updated" ]; then
    echo "[cont-init.d] Installing"
    python3 -m pip install -U --quiet --disable-pip-version-check --break-system-packages /music_library_tools
    rm /music_library_tools/updated
    echo "[cont-init.d] Installation done"
fi
